### ISSUE TITLE
图片显示

### ISSUE THREAD

**Issue by celineyyc** [YuriyGuts/cartpole-q-learning#1]
运行后的结果图片为什么显示不出来曲线啊，还有游戏的页面如何显示

**Comment by YuriyGuts** [comment]
This project was developed a long time ago, and the main libraries it used at the time (primarily OpenAI Gym) are now deprecated or outdated.

Since the project was long overdue for a refresh, I've rebuilt it with modern tooling (https://github.com/YuriyGuts/cartpole-q-learning/pull/2).

Please pull the latest version and follow the installation intructions in README to use the new version.
